FROM centos:latest
ENV PHP_VERSION 5.6.20
ENV ODBC_VERSION 2.3.2
ENV FREETDS_VERSION 0.91

RUN rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm \
    && yum --enablerepo=remi,remi-test install -y libmcrypt libmcrypt-devel

RUN yum update -y \
    && yum upgrade -y

RUN yum install -y libmcrypt-devel libxml2-devel bzip2-devel libjpeg-devel openldap-devel gmp-devel libxslt-devel \
libcurl-devel gcc openssl-devel unixODBC-devel libpng-devel freetype-devel libc-client-devel readline-devel make autoconf libmemcached-devel.x86_64 glibc-common

#Install wget
RUN yum install -y wget nano telnet mc

ADD pb.repo /etc/yum.repos.d/

#add gpgkey
RUN wget http://rpm.web.it.loc/gpgkey -O /tmp/gpgkey &&  rpm --import /tmp/gpgkey && rm -f /tmp/gpgkey

# install unixODBC
RUN curl -O http://soft.web.it.loc/data/unixODBC-$ODBC_VERSION.tar.gz \
    && tar -zxf unixODBC-$ODBC_VERSION.tar.gz \
    && cd unixODBC-$ODBC_VERSION \
                && ./configure \
                    '--prefix=/opt/unixODBC' \
                && make \
                && make install \
                && make clean \
                && cd / \
                && rm -rf unixODBC-$ODBC_VERSION.tar.gz \
                && rm -rf unixODBC-$ODBC_VERSION

# add conf unixODBC
COPY odbc.ini /opt/unixODBC/etc/
COPY odbcinst.ini /opt/unixODBC/etc/

# install freetds
RUN curl -O http://soft.web.it.loc/data/freetds-$FREETDS_VERSION.tar.gz \
    && tar -zxf freetds-$FREETDS_VERSION.tar.gz \
    && cd freetds-$FREETDS_VERSION \
		&& ./configure --prefix=/opt/freetds --with-openssl --disable-debug --enable-msdblib --with-tdsver=8.0 --with-unixodbc=/opt/unixODBC \
		&& make -j4 \
		&& make install \
		&& make clean \
		&& cd / \
		&& rm -rf freetds-$FREETDS_VERSION.tar.gz \
		&& rm -rf freetds-$FREETDS_VERSION
RUN ln -s /opt/freetds/lib /opt/freetds/lib64 && ln -s /opt/freetds/lib/libtdsodbc.so /opt/freetds/lib/libtds.so

# add conf freetds
RUN cd /opt/freetds/etc/ && rm freetds.conf
ADD freetds.conf /opt/freetds/etc/
ADD locales.conf /opt/freetds/etc/

# install php-fpm
RUN curl -O http://soft.web.it.loc/data/php-$PHP_VERSION.tar.gz \
    && tar -zxf php-$PHP_VERSION.tar.gz \
    && cd php-$PHP_VERSION \
		&& ./configure \
		    '--prefix=/opt/php' \
		    '--enable-fpm' \
		    '--with-fpm-user=sybase' \
		    '--with-fpm-group=sybase' \
		    '--enable-bcmath' \
		    '--with-curl' \
		    '--enable-exif' \
		    '--with-gd' \
		    '--with-gmp' \
		    '--enable-mbstring' \
		    '--with-mcrypt' \
		    '--with-mysql' \
		    '--with-mysqli' \
		    '--with-pdo-mysql' \
		    '--enable-soap' \
		    '--enable-zip' \
		    '--with-config-file-path=/opt/php/etc' \
		    '--with-jpeg-dir' \
		    '--with-png-dir' \
		    '--enable-cli' \
		    '--with-freetype-dir' \
		    '--with-libxml-dir' \
		    '--with-xmlrpc' \
		    '--with-openssl' \
		    '--with-pic' \
		    '--disable-rpath' \
		    '--with-bz2' \
		    '--enable-gd-native-ttf' \
		    '--without-gdbm' \
		    '--with-gettext' \
		    '--with-iconv' \
		    '--with-pcre-regex' \
		    '--with-zlib' \
		    '--with-layout=GNU' \
		    '--enable-ftp' \
		    '--enable-sockets' \
		    '--enable-sysvsem' \
		    '--enable-sysvshm' \
		    '--enable-sysvmsg' \
		    '--enable-wddx' \
		    '--enable-shmop' \
		    '--enable-calendar' \
		    '--with-xsl' \
		    '--disable-dba' \
		    '--without-unixODBC' \
		    '--with-readline' \
		    '--enable-xmlreader' \
		    '--with-ldap' \
		    '--with-ldap-sasl' \
		    '--with-libdir=lib64' \
		    '--with-pear' \
		    '--enable-pcntl' \
		&& make -j"$(nproc)" \
		&& make install \
		&& make clean \
		&& cd / \
		&& rm -rf php-$PHP_VERSION.tar.gz
		
# add freetds module php
RUN cd php-$PHP_VERSION/ext/sybase_ct \
		&& /opt/php/bin/phpize \
		&& ./configure --with-php-config=/opt/php/bin/php-config --with-sybase-ct=/opt/freetds \
		&& make \
		&& make install

# add unixODBC module depend
RUN rpm -Uvh http://mirrors.karan.org/epel7/Packages/re2c/20131231011915/0.13.5-1.el6.x86_64/re2c-0.13.5-1.el7.x86_64.rpm

# add unixODBC module php
RUN cd php-$PHP_VERSION/ext/odbc \
                && /opt/php/bin/phpize \
                && sed -ri 's@^ *test +"\$PHP_.*" *= *"no" *&& *PHP_.*=yes *$@#&@g' configure \
                && ./configure --with-php-config=/opt/php/bin/php-config --with-libdir=lib64 --with-unixODBC=/opt/unixODBC \
                && make \
                && make install

# add pdo_odbc
RUN cd php-$PHP_VERSION/ext/pdo_odbc \
		&& /opt/php/bin/phpize \
		&& ./configure --with-php-config=/opt/php/bin/php-config --with-pdo-odbc=unixODBC,/opt/unixODBC \
		&& make \
		&& make install

# add pdo_dblib
RUN cd php-$PHP_VERSION/ext/pdo_dblib \
                && /opt/php/bin/phpize \
		&& ./configure --with-php-config=/opt/php/bin/php-config --with-pdo-dblib=/opt/freetds \
		&& make \
		&& make install \
		&& cd / \
		&& rm -rf php-$PHP_VERSION

# add conf
COPY sites /opt/php/etc/sites
COPY php-fpm.conf /opt/php/etc/
COPY php.ini /opt/php/etc/

RUN mkdir /opt/php/logs && mkdir /opt/php/pid

WORKDIR /opt

RUN useradd sybase && usermod -u 1001 sybase && groupmod -g 1001 sybase
RUN chown -R sybase:sybase /opt/
RUN cp /opt/php/sbin/php-fpm /usr/sbin/
RUN rm -f /etc/odbc.ini
RUN rm -f /etc/odbcinst.ini
RUN ln -s /opt/unixODBC/etc/odbc.ini /etc/odbc.ini
RUN ln -s /opt/unixODBC/etc/odbcinst.ini /etc/odbcinst.ini
RUN rm -f /etc/freetds.conf
RUN ln -s /opt/freetds/etc/freetds.conf /etc/freetds.conf
RUN rm -f /etc/locale.conf
RUN ln -s /opt/freetds/etc/locales.conf /etc/locales.conf

CMD php-fpm -F